# Docker >= 17.04.0
version: "3.2"
services:
  web:
    image: wordpress
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.custom.ini
      - ./data/tmp:/tmp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ''
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: ''
    command: mysqld --max_allowed_packet=256M --innodb-buffer-pool-size=256M --key_buffer_size=32M --query_cache_type=1 --query_cache_size=32M --query_cache_limit=4M --secure-file-priv=""
