version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
