# Docker >= 17.04.0
version: "3.2"
services:
  web:
    container_name: web
    build:
      context: .
      args:
        CACHE_DATE: "20180418"
        APACHE_PORT: "80"
        DEBIAN_FRONTEND: "noninteractive"
        APACHE_RUN_USER: "www-data"
    volumes:
      - ./:/app
    command: /app/run.bash
    expose:
      - "80"
    ports:
      - "80:80"
    links:
      - db
    environment:
      APPLICATION_ENV: "dev"
      APACHE_RUN_USER: "www-data"
      APACHE_RUN_GROUP: "www-data"
      APACHE_LOCK_DIR: "/var/lock/apache2"
      APACHE_RUN_DIR: "/var/run/apache2"
      APACHE_PID_FILE: "/var/run/apache2.pid"
      # arquivo de log do FreeTDS (conector do SQL Server p/ o Cordilheira)
      TDSDUMP: "/tmp/freetds.log"
  db:
    container_name: db
    image: mysql:5.6
    command: mysqld --max_allowed_packet=256M --innodb-buffer-pool-size=256M --key_buffer_size=32M --query_cache_type=1 --query_cache_size=32M --query_cache_limit=4M --secure-file-priv=""
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
